import { describe,it,expect,vi } from "vitest";
vi.mock("server-only",()=>({}));
import example from "../../../config/merchant-payments.example.json";
import { parseMerchantReceivingConfiguration,prepareMerchantReceivingChange } from "./merchant-receiving";
import { loadMerchantReceivingConfiguration } from "./merchant-receiving-loader";
import type {Staff,StaffRole} from "@/lib/staff/permissions";
const config=()=>structuredClone(example);
const staff=(role:StaffRole="super_admin",aal:Staff["aal"]="aal2"):Staff=>({id:"11111111-1111-4111-8111-111111111111",email:"fixture@example.invalid",role,aal,kolId:null,sessionId:"fixture"});
describe("merchant receiver configuration is an isolated disabled template",()=>{
 it("has no implicit configuration or enabled collection path",()=>{expect(loadMerchantReceivingConfiguration(undefined,"other-shop")).toBeNull();expect(loadMerchantReceivingConfiguration(JSON.stringify(config()),example.storeId)?.activation).toBe("disabled");});
 it("refuses activation, private keys, and another shop's configuration",()=>{expect(()=>parseMerchantReceivingConfiguration({...config(),activation:"enabled"},example.storeId)).toThrow();expect(()=>parseMerchantReceivingConfiguration({...config(),privateKey:"not-a-real-key"},example.storeId)).toThrow();expect(()=>parseMerchantReceivingConfiguration(config(),"another-shop")).toThrow("RECEIVER_STORE_MISMATCH");});
 it("does not claim Base or Tron live collection compatibility",()=>{const next=config();next.chains[1].capability="controlled_collection_pilot";expect(()=>parseMerchantReceivingConfiguration(next,example.storeId)).toThrow();const duplicate=config();duplicate.chains[2]=duplicate.chains[1];expect(()=>parseMerchantReceivingConfiguration(duplicate,example.storeId)).toThrow();});
 it("validates chain-specific address syntax without pretending to verify ownership",()=>{const next=config();next.chains[0].merchantReceivingAddress="TInvalid";expect(()=>parseMerchantReceivingConfiguration(next,example.storeId)).toThrow();next.chains[0].merchantReceivingAddress="0x"+"0".repeat(40);expect(()=>parseMerchantReceivingConfiguration(next,example.storeId)).toThrow();next.chains[0].merchantReceivingAddress="0x"+"1".repeat(40);expect(parseMerchantReceivingConfiguration(next,example.storeId).merchantOwnershipAttested).toBe(false);});
 it.each(["admin","operator","catalog_editor","kol","order_operator","analyst"] as StaffRole[])("denies %s receiver changes",role=>{expect(()=>prepareMerchantReceivingChange(staff(role),config(),{...config(),revision:2},example.storeId,"receiver review")).toThrow("STAFF_FORBIDDEN");});
 it("requires MFA, next revision, reason and evidence for an ownership attestation",()=>{expect(()=>prepareMerchantReceivingChange(staff("super_admin","aal1"),config(),{...config(),revision:2},example.storeId,"review")).toThrow("MFA_REQUIRED");expect(()=>prepareMerchantReceivingChange(staff(),config(),config(),example.storeId,"review")).toThrow("RECEIVER_REVISION_CONFLICT");expect(()=>prepareMerchantReceivingChange(staff(),config(),{...config(),revision:2},example.storeId," ")).toThrow("RECEIVER_CHANGE_REASON_REQUIRED");expect(()=>parseMerchantReceivingConfiguration({...config(),merchantOwnershipAttested:true},example.storeId)).toThrow();});
 it("prepares an address-free audit summary while staying disabled",()=>{const next=config();next.revision=2;next.chains[0].merchantReceivingAddress="0x"+"1".repeat(40);const result=prepareMerchantReceivingChange(staff(),config(),next,example.storeId,"reviewed receiver file");expect(result.audit.changedChains).toEqual(["ethereum-mainnet"]);expect(JSON.stringify(result.audit)).not.toContain(next.chains[0].merchantReceivingAddress);expect(result.config.activation).toBe("disabled");});
 it("bounds serialized configuration size",()=>{expect(()=>loadMerchantReceivingConfiguration(" ".repeat(16385),example.storeId)).toThrow("RECEIVER_CONFIG_TOO_LARGE");});
});
