import { describe, expect, it } from "vitest";
import { STAFF_ROLES, STAFF_ACTIONS, permissionAllowed, requirePermission, type Staff, type StaffRole } from "./permissions";
const staff = (role: StaffRole, extra: Partial<Staff> = {}): Staff => ({ id: "named-user", email: "member@example.test", role, kolId: role === "kol" ? "host-a" : null, aal: "aal2", sessionId: "session", ...extra });
describe("staff permission boundaries", () => {
 it.each(STAFF_ROLES)("%s cannot inherit super privileges", role => { expect(permissionAllowed(staff(role), "team.manage")).toBe(role === "super_admin"); expect(permissionAllowed(staff(role), "batch.approve")).toBe(role === "super_admin"); });
 it.each(STAFF_ROLES)("%s batch admission is explicitly allowlisted", role => { expect(permissionAllowed(staff(role), "batch.submit")).toBe(["super_admin", "operator", "catalog_editor", "kol"].includes(role)); });
 it("scopes KOL drafts, pinning and requests to a current assigned host", () => { for (const action of ["live.draft", "live.request", "live.pin"] as const) { expect(permissionAllowed(staff("kol"), action, { kolId: "host-a" })).toBe(true); expect(permissionAllowed(staff("kol"), action, { kolId: "host-b" })).toBe(false); expect(permissionAllowed(staff("kol"), action)).toBe(false); } expect(permissionAllowed(staff("kol", { kolId: null }), "batch.submit")).toBe(false); });
 it("KOL and catalog editors cannot publish streams or approve batches", () => { for (const role of ["kol", "catalog_editor"] as const) { expect(() => requirePermission(staff(role), "live.publish", { kolId: "host-a" })).toThrow("STAFF_FORBIDDEN"); expect(() => requirePermission(staff(role), "batch.approve")).toThrow("STAFF_FORBIDDEN"); } });
 it("order operator cannot edit catalogue, live rooms, roles or analytics", () => { const s = staff("order_operator"); expect(permissionAllowed(s, "orders.read")).toBe(true); expect(permissionAllowed(s, "orders.write")).toBe(true); for (const a of ["catalog.write", "live.publish", "team.manage", "analytics.read", "batch.submit"] as const) expect(permissionAllowed(s, a)).toBe(false); });
 it("operator can review orders but cannot alter fulfillment", () => { expect(permissionAllowed(staff("operator"), "orders.read")).toBe(true); expect(permissionAllowed(staff("operator"), "orders.write")).toBe(false); });
 it("analyst has no mutation, customer-order or batch permissions", () => { const s = staff("analyst"); expect(permissionAllowed(s, "analytics.read")).toBe(true); for (const a of STAFF_ACTIONS.filter(a => !["analytics.read", "catalog.read", "live.read"].includes(a))) expect(permissionAllowed(s, a)).toBe(false); });
 it.each(["super_admin", "operator", "order_operator"] as const)("%s must have verified aal2", role => { for (const action of STAFF_ACTIONS) expect(permissionAllowed(staff(role, { aal: "aal1" }), action)).toBe(false); expect(() => requirePermission(staff(role, { aal: "aal1" }), "catalog.read")).toThrow("MFA_REQUIRED"); });
});
