import { beforeEach, describe, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
const mocks = vi.hoisted(() => ({ staff: vi.fn(), pending: vi.fn(), verified: vi.fn(), invite: vi.fn(), insert: vi.fn(), update: vi.fn(), rpc: vi.fn(), setSession: vi.fn(), listFactors: vi.fn(), challengeAndVerify: vi.fn(), enroll: vi.fn(), unenroll: vi.fn() }));
vi.mock("@/lib/env", () => ({ getSiteUrl: () => "https://www.isuntvmall.com" }));
vi.mock("@/lib/staff/auth", async () => {
 const permissions = await import("./permissions"); return { ...permissions, STAFF_COOKIE: "isun_staff", STAFF_PENDING_COOKIE: "isun_staff_pending", STAFF_PENDING_REFRESH_COOKIE: "isun_staff_pending_refresh", requireStaff: mocks.staff, resolveStaffFromToken: mocks.pending, staffFromToken: mocks.verified, cookieToken: (_r: Request, name: string) => name.endsWith("refresh") ? "refresh" : "access", requireStaffOrigin: (r: Request) => { if (r.headers.get("origin") !== "https://www.isuntvmall.com") throw new permissions.StaffError("INVALID_ORIGIN", 403); }, staffCookieOptions: (maxAge = 3600) => ({ httpOnly: true, secure: true, sameSite: "strict", path: "/", maxAge }), staffAuthClient: () => ({ auth: { setSession: mocks.setSession, mfa: { listFactors: mocks.listFactors, challengeAndVerify: mocks.challengeAndVerify, enroll: mocks.enroll, unenroll: mocks.unenroll } } }) };
});
vi.mock("@/lib/supabase/admin", () => ({ getSupabaseAdmin: () => ({ auth: { admin: { inviteUserByEmail: mocks.invite } }, rpc: mocks.rpc, from: () => ({ insert: mocks.insert, update: (body: unknown) => ({ eq: () => mocks.update(body) }) }) }) }));
import { POST as invite } from "@/app/api/admin/team/invite/route";
import { POST as mfa } from "@/app/api/admin/mfa/route";
const member = { id: "11111111-1111-4111-8111-111111111111", role: "super_admin", aal: "aal2", kolId: null, email: "owner@example.test", sessionId: "22222222-2222-4222-8222-222222222222" };
const factor = "33333333-3333-4333-8333-333333333333";
const request = (path: string, body: unknown, origin = "https://www.isuntvmall.com") => new Request(`https://www.isuntvmall.com${path}`, { method: "POST", headers: { "Content-Type": "application/json", origin }, body: JSON.stringify(body) });
const invitation = { requestId: "44444444-4444-4444-8444-444444444444", email: "new@example.test", role: "analyst", kolId: null };
beforeEach(() => { vi.clearAllMocks(); mocks.staff.mockResolvedValue(member); mocks.pending.mockResolvedValue({ ...member, aal: "aal1" }); mocks.verified.mockResolvedValue(member); mocks.insert.mockResolvedValue({ error: null }); mocks.update.mockResolvedValue({ error: null }); mocks.rpc.mockResolvedValue({ error: null }); mocks.invite.mockResolvedValue({ data: { user: { id: "55555555-5555-4555-8555-555555555555" } }, error: null }); mocks.setSession.mockResolvedValue({ data: { user: { id: member.id } }, error: null }); mocks.listFactors.mockResolvedValue({ data: { totp: [{ id: factor, status: "verified" }], all: [{ id: factor, status: "verified", factor_type: "totp" }] }, error: null }); mocks.challengeAndVerify.mockResolvedValue({ data: { access_token: "verified-access", expires_in: 3600 }, error: null }); });
describe("team invitation gate", () => {
 it.each(["operator", "catalog_editor", "kol", "order_operator", "analyst"])("%s cannot send invitations", async role => { mocks.staff.mockResolvedValue({ ...member, role }); const r = await invite(request("/api/admin/team/invite", invitation)); expect(r.status).toBe(403); expect(mocks.invite).not.toHaveBeenCalled(); });
 it("super administrator at aal1 cannot send invitations", async () => { mocks.staff.mockResolvedValue({ ...member, aal: "aal1" }); expect((await invite(request("/api/admin/team/invite", invitation))).status).toBe(403); expect(mocks.invite).not.toHaveBeenCalled(); });
 it("cross-origin request cannot send", async () => { expect((await invite(request("/api/admin/team/invite", invitation, "https://evil.test"))).status).toBe(403); expect(mocks.invite).not.toHaveBeenCalled(); });
 it("repeated request ID never resends email", async () => { mocks.insert.mockResolvedValue({ error: { code: "23505" } }); const r = await invite(request("/api/admin/team/invite", invitation)); expect(await r.json()).toMatchObject({ code: "INVITE_ALREADY_REQUESTED" }); expect(mocks.invite).not.toHaveBeenCalled(); });
 it("membership failure remains pending and does not claim granted access", async () => { mocks.rpc.mockResolvedValue({ error: new Error("revoked actor") }); const r = await invite(request("/api/admin/team/invite", invitation)); expect(r.status).toBe(409); expect(await r.json()).toMatchObject({ code: "INVITE_MEMBERSHIP_PENDING" }); expect(mocks.update).toHaveBeenCalledWith(expect.objectContaining({ status: "membership_pending" })); expect(mocks.update).not.toHaveBeenCalledWith(expect.objectContaining({ status: "ready" })); });
 it("provider failure never grants membership", async () => { mocks.invite.mockResolvedValue({ data: { user: null }, error: new Error("mail") }); expect((await invite(request("/api/admin/team/invite", invitation))).status).toBe(409); expect(mocks.rpc).not.toHaveBeenCalled(); });
 it("explicit requested role and actor are passed to guarded membership RPC", async () => { const r = await invite(request("/api/admin/team/invite", invitation)); expect(r.status).toBe(200); expect(mocks.invite).toHaveBeenCalledWith("new@example.test", { redirectTo: "https://www.isuntvmall.com/admin/invite" }); expect(mocks.rpc).toHaveBeenCalledWith("staff_set_member", { p_actor: member.id, p_target: "55555555-5555-4555-8555-555555555555", p_role: "analyst", p_active: true, p_kol: null }); });
});
describe("MFA session promotion", () => {
 it("rejects a factor not belonging to the pending identity", async () => { const r = await mfa(request("/api/admin/mfa", { action: "verify", factorId: "66666666-6666-4666-8666-666666666666", code: "123456" })); expect(r.status).toBe(403); expect(mocks.challengeAndVerify).not.toHaveBeenCalled(); });
 it("failed verification cannot issue staff cookie", async () => { mocks.challengeAndVerify.mockResolvedValue({ data: null, error: new Error("invalid") }); const r = await mfa(request("/api/admin/mfa", { action: "verify", factorId: factor, code: "123456" })); expect(r.status).toBe(401); expect(r.headers.get("set-cookie")).toBeNull(); });
 it("provider response alone is insufficient without freshly verified aal2", async () => { mocks.verified.mockResolvedValue({ ...member, aal: "aal1" }); const r = await mfa(request("/api/admin/mfa", { action: "verify", factorId: factor, code: "123456" })); expect(r.status).toBe(403); expect(r.headers.get("set-cookie")).toBeNull(); });
 it("does not promote a different returned identity", async () => { mocks.verified.mockResolvedValue({ ...member, id: "other" }); expect((await mfa(request("/api/admin/mfa", { action: "verify", factorId: factor, code: "123456" }))).status).toBe(403); });
 it("only verified matching aal2 gets HttpOnly staff cookie", async () => { const r = await mfa(request("/api/admin/mfa", { action: "verify", factorId: factor, code: "123456" })); expect(r.status).toBe(200); expect(r.headers.get("set-cookie")).toContain("isun_staff=verified-access"); expect(r.headers.get("set-cookie")).toContain("HttpOnly"); expect(mocks.verified).toHaveBeenCalledWith("verified-access"); });
 it("existing verified factor setup never replaces a verified factor", async () => { const r = await mfa(request("/api/admin/mfa", { action: "setup" })); expect(await r.json()).toMatchObject({ enrolled: true, factorId: factor }); expect(mocks.unenroll).not.toHaveBeenCalled(); expect(mocks.enroll).not.toHaveBeenCalled(); });
});
