import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
const m = vi.hoisted(() => ({ rpc: vi.fn(), single: vi.fn(), intent: vi.fn(), charge: vi.fn(), list: vi.fn(), create: vi.fn(), retrieve: vi.fn(), identity: vi.fn() }));
vi.mock("@/lib/supabase/admin", () => ({ getSupabaseAdmin: () => ({ rpc: m.rpc, from: () => ({ select: () => ({ eq: () => ({ single: m.single }) }) }) }) }));
vi.mock("@/lib/stripe/runtime", () => ({ verifyPaymentIdentity: m.identity, frozenPaymentIdentity: () => ({ accountId: "acct_fixture", livemode: false }), assertProviderMode: (i: { livemode: boolean }, o: { livemode: boolean }) => { if (i.livemode !== o.livemode) throw Error("mode"); } }));
vi.mock("@/lib/stripe/client", () => ({ getStripe: () => ({ paymentIntents: { retrieve: m.intent }, charges: { retrieve: m.charge }, refunds: { list: m.list, create: m.create, retrieve: m.retrieve } }) }));
import { executeApprovedRefund, reconcileOrder } from "./stripe";
const command = { id: "command", order_id: "order", account_id: "acct_fixture", livemode: false, payment_intent_id: "pi_fixture", charge_id: "ch_fixture", amount: 1000, currency: "hkd", expected_refunded_before: 0, idempotency_key: "stable-key", provider_refund_id: null, status: "processing", lease_token: "lease", action: "create" };
const refund = { id: "re_fixture", payment_intent: "pi_fixture", charge: "ch_fixture", amount: 1000, currency: "hkd", status: "succeeded", metadata: { commerce_command_id: "command" } };
beforeEach(() => {
 vi.resetAllMocks(); vi.stubEnv("STRIPE_REFUNDS_ENABLED", "true");
 m.identity.mockResolvedValue({ accountId: "acct_fixture", livemode: false });
 m.single.mockResolvedValue({ data: { id: "order", total_amount: 1000, currency: "hkd", stripe_payment_intent_id: "pi_fixture", checkout_policy: {} } });
 m.rpc.mockImplementation(async (name: string, args: { p_outcome?: string }) => ({ data: name === "finance_refund_complete" ? { id: "command", status: args.p_outcome } : command, error: null }));
 m.intent.mockResolvedValue({ id: "pi_fixture", livemode: false, status: "succeeded", latest_charge: "ch_fixture" });
 m.charge.mockResolvedValue({ id: "ch_fixture", livemode: false, payment_intent: "pi_fixture", paid: true, amount_captured: 1000, amount_refunded: 0, currency: "hkd", balance_transaction: null });
 m.list.mockResolvedValue({ data: [], has_more: false }); m.create.mockResolvedValue(refund);
});
afterEach(() => vi.unstubAllEnvs());
describe("refund adapter: mocked provider, no funds", () => {
 it("disabled template performs no DB or provider action", async () => { vi.stubEnv("STRIPE_REFUNDS_ENABLED", "false"); await expect(executeApprovedRefund("actor", "order", "approval", "request")).rejects.toThrow("REFUNDS_DISABLED"); expect(m.rpc).not.toHaveBeenCalled(); });
 it("full remaining amount comes from durable approved command, same idempotency key", async () => { await executeApprovedRefund("actor", "order", "approval", "request"); expect(m.create).toHaveBeenCalledWith(expect.objectContaining({ amount: 1000, payment_intent: "pi_fixture" }), { idempotencyKey: "stable-key" }); expect(m.rpc).toHaveBeenCalledWith("finance_refund_complete", expect.objectContaining({ p_outcome: "succeeded", p_facts: expect.objectContaining({ accountId: "acct_fixture", amount: 1000 }) })); });
 it("network timeout is unknown and keeps command/key", async () => { m.create.mockRejectedValue(Error("timeout")); await expect(executeApprovedRefund("actor", "order", "approval", "request")).rejects.toThrow("REFUND_OUTCOME_UNKNOWN"); expect(m.rpc).toHaveBeenCalledWith("finance_refund_complete", expect.objectContaining({ p_command: "command", p_outcome: "unknown" })); });
 it("recovered provider refund is reconciled without another create", async () => { m.list.mockResolvedValue({ data: [refund], has_more: false }); await executeApprovedRefund("actor", "order", "approval", "request"); expect(m.create).not.toHaveBeenCalled(); });
 it("after retry cutoff, missing refund is held, never recreated", async () => { m.rpc.mockResolvedValue({ data: { ...command, action: "reconcile" }, error: null }); await expect(executeApprovedRefund("actor", "order", "approval", "request")).rejects.toThrow("REFUND_OUTCOME_UNKNOWN"); expect(m.create).not.toHaveBeenCalled(); });
 it("external partial refund prevents stale-amount execution", async () => { m.charge.mockResolvedValue({ id: "ch_fixture", livemode: false, payment_intent: "pi_fixture", paid: true, amount_captured: 1000, amount_refunded: 100, currency: "hkd", balance_transaction: null }); await expect(executeApprovedRefund("actor", "order", "approval", "request")).rejects.toThrow(); expect(m.create).not.toHaveBeenCalled(); });
 it("truncated refund history cannot authorize execution", async () => { m.list.mockResolvedValue({ data: [], has_more: true }); await expect(executeApprovedRefund("actor", "order", "approval", "request")).rejects.toThrow(); expect(m.create).not.toHaveBeenCalled(); });
 it("unknown fee and net remain null", async () => { await reconcileOrder("actor", "order"); expect(m.rpc).toHaveBeenCalledWith("finance_record_reconciliation", expect.objectContaining({ p_facts: expect.objectContaining({ fee: null, net: null }) })); });
 it("failed identity verification prevents even command creation", async () => { m.identity.mockRejectedValue(Error("wrong merchant")); await expect(executeApprovedRefund("actor", "order", "approval", "request")).rejects.toThrow(); expect(m.rpc).not.toHaveBeenCalled(); expect(m.create).not.toHaveBeenCalled(); });
 it("wrong intent response is held before money creation", async () => { m.intent.mockResolvedValue({ id: "pi_other", livemode: false, status: "succeeded", latest_charge: "ch_fixture" }); await expect(executeApprovedRefund("actor", "order", "approval", "request")).rejects.toThrow("REFUND_OUTCOME_UNKNOWN"); expect(m.create).not.toHaveBeenCalled(); });
 it("foreign charge in refund history cannot authorize new money", async () => { m.list.mockResolvedValue({ data: [{ ...refund, charge: "ch_other" }], has_more: false }); await expect(executeApprovedRefund("actor", "order", "approval", "request")).rejects.toThrow("REFUND_OUTCOME_UNKNOWN"); expect(m.create).not.toHaveBeenCalled(); });
 it("a substituted prepared command is rejected before claiming", async () => { m.rpc.mockResolvedValue({ data: { ...command, order_id: "other-order" }, error: null }); await expect(executeApprovedRefund("actor", "order", "approval", "request")).rejects.toThrow("PAYMENT_IDENTITY_MISMATCH"); expect(m.rpc).not.toHaveBeenCalledWith("finance_refund_claim", expect.anything()); expect(m.create).not.toHaveBeenCalled(); });
 it("requires-action refund stays pending", async () => { m.create.mockResolvedValue({ ...refund, status: "requires_action" }); const result = await executeApprovedRefund("actor", "order", "approval", "request"); expect(result.status).toBe("pending"); expect(m.rpc).toHaveBeenCalledWith("finance_refund_complete", expect.objectContaining({ p_outcome: "pending" })); });
 it("confirmation arriving during timeout recovery returns confirmed success", async () => { m.create.mockRejectedValue(Error("response lost")); m.rpc.mockImplementation(async (name: string) => ({ data: name === "finance_refund_complete" ? { id: command.id, status: "succeeded" } : command, error: null })); await expect(executeApprovedRefund("actor", "order", "approval", "request")).resolves.toEqual({ id: "command", status: "succeeded" }); expect(m.create).toHaveBeenCalledTimes(1); });
 it("database outage after provider creation remains unknown without another create", async () => { m.rpc.mockImplementation(async (name: string) => ({ data: name === "finance_refund_complete" ? null : command, error: name === "finance_refund_complete" ? { message: "private provider details" } : null })); await expect(executeApprovedRefund("actor", "order", "approval", "request")).rejects.toThrow("REFUND_OUTCOME_UNKNOWN"); expect(m.create).toHaveBeenCalledTimes(1); expect(m.rpc).toHaveBeenCalledWith("finance_refund_complete", expect.objectContaining({ p_outcome: "unknown", p_command: command.id })); });

});
