"use client";
import {useEffect,useState} from "react";
import {useLocale} from "@/components/i18n/locale-provider";
import type {AdmissionPolicy} from "@/lib/checkout/admission-schema";
export function CheckoutPolicy(){
 const{t}=useLocale();const[policy,setPolicy]=useState<AdmissionPolicy|null>(null);const[configured,setConfigured]=useState(false);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
 useEffect(()=>{const controller=new AbortController();fetch("/api/admin/checkout-policy",{cache:"no-store",signal:controller.signal}).then(async response=>{if(!response.ok)throw Error();const result=await response.json();setPolicy(result.policy);setConfigured(result.verificationConfigured);}).catch(()=>{if(!controller.signal.aborted)setNotice("load");});return()=>controller.abort();},[]);
 async function save(){if(!policy)return;setBusy(true);setNotice("");try{const response=await fetch("/api/admin/checkout-policy",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({enabled:policy.enabled,maxRecent:policy.max_recent_attempts,maxClientActive:policy.max_client_active,maxStoreActive:policy.max_store_active})});if(!response.ok)throw Error();setPolicy((await response.json()).policy);setNotice("saved");}catch{setNotice("save");}finally{setBusy(false);}}
 return <section><h3>{t("Checkout admission limits","結帳受理限制")}</h3><p>{t("Limits protect stock from too many simultaneous holds. Saving them does not open checkout or change payment settings. A separate verified release is still required.","限制可避免過多同時請求佔用庫存。儲存限制不會開放結帳或更改付款設定，仍須另行完成發布驗證。")}</p>{policy&&<form className="admin-form-grid" onSubmit={event=>{event.preventDefault();void save();}}><label><input type="checkbox" checked={policy.enabled} disabled={busy||(!configured&&!policy.enabled)} onChange={e=>setPolicy({...policy,enabled:e.target.checked})}/>{t("Allow new verified attempts","允許新的已驗證請求")}</label>{([["max_recent_attempts","New attempts per connection in 15 minutes","每條連線十五分鐘內的新請求",100],["max_client_active","Active holds per connection","每條連線的有效預留",20],["max_store_active","Active holds across the store","全店有效預留",10000]] as const).map(([key,en,zh,max])=><label key={key}>{t(en,zh)}<input type="number" required min={1} max={max} value={policy[key]} disabled={busy} onChange={e=>setPolicy({...policy,[key]:Number(e.target.value)})}/></label>)}<button className="button" disabled={busy}>{t("Save limits","儲存限制")}</button></form>}{!configured&&<p>{t("Verification settings are not configured; new attempts cannot be enabled here.","驗證設定尚未完成，暫時無法在此啟用新請求。")}</p>}{notice&&<p role="status">{notice==="saved"?t("Limits saved. Checkout release status is unchanged.","限制已儲存，結帳發布狀態維持不變。"):notice==="load"?t("Limits could not be loaded. No default values were substituted.","未能載入限制，沒有以預設值代替。"):t("The update could not be confirmed. Reload before making another change.","未能確認更新，請重新載入後再作更改。")}</p>}</section>;
}
