"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import { useLocale } from "@/components/i18n/locale-provider";
import { merchantOperationsCopy } from "./merchant-operations-copy";
import { INTL_LOCALES } from "@/lib/i18n";
import type { FinanceOrderView,FinancePageView } from "@/lib/finance/view";
const operationLabels={en:{pending:"Pending",processing:"Processing",unknown:"Not verified",prepared:"Prepared",submitted:"Submitted",succeeded:"Succeeded",failed:"Failed",uncertain:"Needs reconciliation"},"zh-Hant":{pending:"待處理",processing:"處理中",unknown:"尚未核實",prepared:"已準備",submitted:"已提交",succeeded:"成功",failed:"失敗",uncertain:"待對帳"},"zh-Hans":{pending:"待处理",processing:"处理中",unknown:"尚未核实",prepared:"已准备",submitted:"已提交",succeeded:"成功",failed:"失败",uncertain:"待对账"},ja:{pending:"保留中",processing:"処理中",unknown:"未確認",prepared:"準備完了",submitted:"送信済み",succeeded:"成功",failed:"失敗",uncertain:"照合が必要"}};
function stableRefundKey(orderId:string,refundId:string,fallback:Map<string,string>){const key=`merchant-refund-request:${orderId}:${refundId}`;try{const saved=sessionStorage.getItem(key);if(saved)return saved;const value=fallback.get(key)||crypto.randomUUID();sessionStorage.setItem(key,value);return value;}catch{const value=fallback.get(key)||crypto.randomUUID();fallback.set(key,value);return value;}}
export function FinanceWorkspace(){const{locale}=useLocale();const c=merchantOperationsCopy[locale];const[page,setPage]=useState(0);const[data,setData]=useState<FinancePageView>({orders:[],commands:[],snapshots:[],page:0,hasMore:false});const[busy,setBusy]=useState(false);const[loading,setLoading]=useState(true);const[notice,setNotice]=useState<""|"loadError"|"updateError">("");const sequence=useRef(0);const keys=useRef(new Map<string,string>());
 const load=useCallback(async()=>{const token=++sequence.current;setLoading(true);try{const r=await fetch(`/api/admin/finance?page=${page}`,{cache:"no-store"});const body=await r.json();if(!r.ok)throw Error();if(token===sequence.current){setData(body);setNotice("");}}catch{if(token===sequence.current)setNotice("loadError");}finally{if(token===sequence.current)setLoading(false);}},[page]);useEffect(()=>{const current=sequence;const timer=setTimeout(()=>void load(),0);return()=>{clearTimeout(timer);current.current++;};},[load]);
 async function act(order:FinanceOrderView,refundRequestId?:string){setBusy(true);setNotice("");const body=refundRequestId?{action:"refund",orderId:order.id,refundRequestId,requestId:stableRefundKey(order.id,refundRequestId,keys.current)}:{action:"reconcile",orderId:order.id};try{const r=await fetch("/api/admin/finance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw Error();await load();}catch{setNotice("updateError");}finally{setBusy(false);}}
 return <section className="admin-table-card"><div className="admin-card-heading"><h2>{c.finance}</h2><button disabled={busy||loading} onClick={()=>void load()}>{c.refresh}</button></div><p>{c.financeIntro}</p><a className="text-link" href={`/api/admin/finance?format=csv&page=${page}`}>{c.csv}</a>{notice&&<p role="alert">{c[notice]}</p>}{loading&&<p role="status">{c.loading}</p>}{!loading&&data.orders.map(order=><FinanceCard key={`${order.id}:${order.reconciledAt}:${order.remainingAmount}:${order.refundState}`} order={order} busy={busy} onAction={act}/>)}{!loading&&!data.orders.length&&!notice&&<p>{c.empty}</p>}{data.commands.length>0&&<details><summary>{c.history}</summary>{data.commands.map(command=><p key={command.id}>{command.orderId} · {operationLabels[locale][command.status as keyof typeof operationLabels.en]||c.unknown} · {command.providerReference||c.unknown} · <time>{command.createdAt}</time></p>)}</details>}<div className="batch-actions"><button disabled={!page||busy||loading} onClick={()=>setPage(page-1)}>{c.previous}</button><span>{page+1}</span><button disabled={!data.hasMore||busy||loading} onClick={()=>setPage(page+1)}>{c.next}</button></div></section>;
}
function FinanceCard({order,busy,onAction}:{order:FinanceOrderView;busy:boolean;onAction:(order:FinanceOrderView,refundRequestId?:string)=>Promise<void>}){const{locale}=useLocale();const c=merchantOperationsCopy[locale];const[confirmed,setConfirmed]=useState(false);const approved=order.refundRequests.find(request=>request.status==="approved");const money=(value:number|null)=>value===null?c.unknown:new Intl.NumberFormat(INTL_LOCALES[locale],{style:"currency",currency:order.currency.toUpperCase()}).format(value/100);const canRefund=order.canRefund&&Boolean(approved)&&Boolean(order.merchantAccountId)&&Boolean(order.mode)&&order.remainingAmount!==null&&order.remainingAmount>0;return <article className="admin-order-card"><h3>{order.id}</h3><dl><dt>{c.account}</dt><dd>{order.merchantAccountId||c.unknown}</dd><dt>{c.mode}</dt><dd>{order.mode?c[order.mode]:c.unknown}</dd><dt>{c.amount}</dt><dd>{money(order.paidAmount)}</dd><dt>{c.remaining}</dt><dd><strong>{money(order.remainingAmount)}</strong></dd><dt>{c.reference}</dt><dd>{order.paymentReference||c.unknown}</dd><dt>{c.checked}</dt><dd>{order.reconciledAt||c.unknown}</dd></dl><button className="button button-secondary" disabled={busy} onClick={()=>void onAction(order)}>{c.reconcile}</button>{approved?<div><p>{c.approved}: {approved.id}</p><p>{approved.reason}</p>{!order.canRefund&&<p>{c.refundUncertain}</p>}<label><input type="checkbox" checked={confirmed} disabled={busy||!canRefund} onChange={e=>setConfirmed(e.target.checked)}/>{c.confirm}</label><button className="button" disabled={busy||!confirmed||!canRefund} onClick={()=>{setConfirmed(false);void onAction(order,approved.id);}}>{c.refund} · {money(order.remainingAmount)}</button></div>:<p>{c.noApproval}</p>}</article>;}
