"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import { useLocale } from "@/components/i18n/locale-provider";
import { merchantOperationsCopy } from "./merchant-operations-copy";
import type { StockItem,StockPage } from "@/lib/inventory/contracts";
export function InventoryWorkspace(){
 const{locale,localize}=useLocale();const c=merchantOperationsCopy[locale];const[data,setData]=useState<StockPage>({items:[],count:0,page:0});const[page,setPage]=useState(0);const[search,setSearch]=useState("");const[notice,setNotice]=useState<""|"loadError"|"updateError"|"conflict"|"success">("");const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const sequence=useRef(0);const keys=useRef(new Map<string,string>());
 const load=useCallback(async()=>{const token=++sequence.current;setLoading(true);try{const r=await fetch(`/api/admin/inventory?${new URLSearchParams({page:String(page),search})}`,{cache:"no-store"});const body=await r.json();if(!r.ok)throw Error();if(token===sequence.current){setData(body);setNotice("");}}catch{if(token===sequence.current)setNotice("loadError");}finally{if(token===sequence.current)setLoading(false);}},[page,search]);
 useEffect(()=>{const current=sequence;const timer=setTimeout(()=>void load(),180);return()=>{clearTimeout(timer);current.current++;};},[load]);
 async function adjust(item:StockItem,stockQty:number,reason:string){setBusy(true);const fingerprint=JSON.stringify([item.id,item.revision,stockQty,reason]);const requestId=keys.current.get(fingerprint)||crypto.randomUUID();keys.current.set(fingerprint,requestId);try{const r=await fetch("/api/admin/inventory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId:item.id,revision:item.revision,requestId,stockQty,reason})});const body=await r.json();if(!r.ok){setNotice(body.code==="STALE_STOCK_REVISION"?"conflict":"updateError");return;}keys.current.delete(fingerprint);await load();setNotice("success");}catch{setNotice("updateError");}finally{setBusy(false);}}
 return <section className="admin-table-card"><div className="admin-card-heading"><h2>{c.inventory}</h2><button disabled={busy||loading} onClick={()=>void load()}>{c.refresh}</button></div><p>{c.inventoryIntro}</p><label>{c.search}<input value={search} maxLength={100} disabled={busy} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label>{notice&&<p role="alert">{c[notice]}</p>}{loading&&<p role="status">{c.loading}</p>}{!loading&&data.items.map(item=><InventoryCard key={`${item.id}-${item.revision}`} item={{...item,title:localize(item.title)}} busy={busy} adjust={adjust}/>)}{!loading&&!data.items.length&&!notice&&<p>{c.empty}</p>}<div className="batch-actions"><button disabled={!page||busy||loading} onClick={()=>setPage(page-1)}>{c.previous}</button><span>{page+1} / {Math.max(1,Math.ceil(data.count/25))}</span><button disabled={(page+1)*25>=data.count||busy||loading} onClick={()=>setPage(page+1)}>{c.next}</button></div></section>;
}
function InventoryCard({item,busy,adjust}:{item:StockItem;busy:boolean;adjust:(item:StockItem,quantity:number,reason:string)=>Promise<void>}){const{locale}=useLocale();const c=merchantOperationsCopy[locale];const[quantity,setQuantity]=useState(String(item.stockQty));const[reason,setReason]=useState("");return <article className="admin-order-card"><h3>{item.title}</h3><p>{item.sku} · {c.available}: {item.availableQty} · {c.reserved}: {item.reservedQty}</p><form className="admin-form-grid" onSubmit={e=>{e.preventDefault();void adjust(item,Number(quantity),reason.trim());}}><label>{c.target}<input type="number" min={item.reservedQty} max={100000000} step={1} required value={quantity} disabled={busy} onChange={e=>setQuantity(e.target.value)}/></label><label>{c.reason}<textarea required minLength={1} maxLength={1000} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label><button className="button button-secondary" disabled={busy||!reason.trim()||!quantity||Number(quantity)===item.stockQty}>{c.save}</button></form></article>;}
