"use client";
import { useRef, useState } from "react";
import { useLocale } from "@/components/i18n/locale-provider";
import { buildLiveEmbed } from "@/lib/live/adapters";
import { productTitle } from "@/lib/product-copy";
import { liveDraftSchema, type LiveDraft, type LiveDraftPayload, type LiveControl, type LiveSourceCheck } from "@/lib/live/operations-schema";
import type { StaffRole } from "@/lib/staff/permissions";
import type { Kol, Product } from "@/types/commerce";
import "./live-admin-workspace.css";

type Detail = { draft: LiveDraft; sourceCheck: LiveSourceCheck | null; control: LiveControl | null; publishedProductIds: string[] };
function fresh(kolId: string | null, kols: Kol[]): LiveDraftPayload {
  const host = kols.find(kol => kol.id === kolId);
  return { slug: "", title: "", titleZh: "", description: "", descriptionZh: "", hostName: host?.displayName || "", kolId: kolId || "", platform: "youtube", externalUrl: "", embedId: null, status: "scheduled", startsAt: new Date(Date.now() + 3600000).toISOString(), endsAt: null, posterUrl: null, productIds: [] };
}
function dateInput(value: string | null) { if (!value) return ""; const d = new Date(value); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
async function call(path: string, body?: unknown) {
  const response = await fetch(path, { cache: "no-store", ...(body ? { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) } : {}) });
  const result = await response.json(); if (!response.ok) throw new Error(result.code || "LIVE_OPERATION_FAILED"); return result;
}
const errors: Record<string, [string, string]> = {
  STALE_LIVE_REVISION: ["Another edit arrived. Reload the saved room before trying again.", "此直播間已有其他修改，請重新載入已儲存版本後再試。"],
  STALE_PIN_REVISION: ["The live selection changed. Reload the room before pinning again.", "直播精選已有更新，請重新載入後再置頂商品。"],
  SOURCE_NOT_VERIFIED: ["An operator must verify this exact room revision's source within the last 24 hours.", "營運人員須在最近 24 小時內驗證此確切版本的直播來源。"],
  PRODUCT_NOT_APPROVED: ["Every selected product must be published, approved merchandise. Sample products cannot be published into a real room.", "所選商品必須為已核准刊登的商品；示範商品不可加入正式公開直播間。"],
  EMPTY_LIVE_RAIL: ["Choose at least one approved product before publishing.", "公開前請選擇至少一件核准商品。"],
  LIVE_SLUG_IN_USE: ["That room address is already in use. Choose another.", "此直播間網址已被使用，請選擇其他名稱。"],
  ROOM_NOT_LIVE: ["Product pinning is available only while the published room is live.", "只有已公開且正在直播的直播間可以置頂商品。"],
  SOURCE_CHANGE_REQUIRES_OPERATOR: ["Ask an operator to change a saved room's broadcast source.", "請由營運人員修改已儲存直播間的播放來源。"],
  INVALID_INPUT: ["Check the required fields, platform URL, unique products and dates.", "請檢查必填欄位、平台網址、商品是否重複及日期。"],
  SIGN_IN_REQUIRED: ["Sign in again, then reload this room.", "請重新登入，再載入此直播間。"],
  MFA_REQUIRED: ["Complete two-step verification before this operation.", "請完成兩步驗證後再操作。"],
};

export function AdminLiveWorkspace({ initialDrafts, initialCount, products, kols, role, kolId }: { initialDrafts: LiveDraft[]; initialCount?: number; products: Product[]; kols: Kol[]; role: StaffRole; kolId: string | null }) {
  const { t, locale, localize } = useLocale(); const operator = role === "super_admin" || role === "operator"; const writable = operator || role === "kol";
  const [drafts, setDrafts] = useState(initialDrafts); const [detail, setDetail] = useState<Detail | null>(null);
  const [payload, setPayload] = useState(() => fresh(kolId, kols)); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  const [mode, setMode] = useState<"embedded" | "external_link">("external_link"); const [rights, setRights] = useState(false); const [playback, setPlayback] = useState(false); const [deviceNote, setDeviceNote] = useState("");
  const [page, setPage] = useState(0); const [count, setCount] = useState(initialCount ?? initialDrafts.length); const newId = useRef<string | null>(null);
  const approved = products.filter(product => product.status === "published" && !product.isDemo);
  const activeHosts = kols.filter(kol => kol.status === "active" && (role !== "kol" || kol.id === kolId));
  function change<K extends keyof LiveDraftPayload>(key: K, value: LiveDraftPayload[K]) { setPayload(current => ({ ...current, [key]: value })); }
  function applyDetail(result: Detail) { setDetail(result); setPayload(result.draft.payload); setMode(result.sourceCheck?.playback_mode || "external_link"); setRights(false); setPlayback(false); setDeviceNote(""); }
  async function list(index = page) { const result = await call(`/api/admin/live?page=${index}`); setDrafts(result.drafts); setCount(result.count); setPage(index); }
  async function load(id: string) { setBusy(true); setNotice(""); try { applyDetail(await call(`/api/admin/live/${id}`)); } catch (error) { setNotice(error instanceof Error ? error.message : "LIVE_OPERATION_FAILED"); } finally { setBusy(false); } }
  async function action(body: Record<string, unknown>) {
    setBusy(true); setNotice("");
    try {
      const id = detail?.draft.id || (newId.current ||= crypto.randomUUID());
      const result = await call(`/api/admin/live/${id}`, body); applyDetail(result); await list(); setNotice("SAVED");
    } catch (error) { setNotice(error instanceof Error ? error.message : "LIVE_OPERATION_FAILED"); } finally { setBusy(false); }
  }
  async function save(event: React.FormEvent) { event.preventDefault(); const checked = liveDraftSchema.safeParse(payload); if (!checked.success) { setNotice("INVALID_INPUT"); return; } await action({ action: "save", revision: detail?.draft.revision || 0, payload: checked.data }); }
  function move(id: string, direction: number) { const ids = [...payload.productIds]; const i = ids.indexOf(id), target = i + direction; if (target < 0 || target >= ids.length) return; [ids[i], ids[target]] = [ids[target], ids[i]]; change("productIds", ids); }
  const copy = errors[notice] || ["The operation could not finish. Reload and check the saved state before retrying.", "操作未能完成，請重新載入並檢查已儲存狀態後再試。"];
  const previewEmbed = detail ? buildLiveEmbed(detail.draft.payload.platform, detail.draft.payload.externalUrl, detail.draft.payload.embedId) : null;
  const dirty = detail ? JSON.stringify(detail.draft.payload) !== JSON.stringify(payload) : true;
  return <div className="live-operations">
    <div className="admin-card-heading"><div><span className="eyebrow">{t("LIVE STUDIO", "直播工作室")}</span><h2>{t("Each host. Their own room.", "每位主播，自己的直播間。")}</h2></div>{writable && <button className="button button-secondary" disabled={busy} onClick={() => { setDetail(null); setPayload(fresh(kolId, kols)); newId.current = null; setNotice(""); setRights(false); setPlayback(false); }}>{t("New room", "新增直播間")}</button>}</div>
    <p>{t("Save a private draft, verify the broadcast, then publish its approved product selection. Shopping bags stay with viewers between rooms.", "先儲存私人草稿，驗證播放來源，再公開核准商品組合。觀眾切換直播間時會保留購物袋。")}</p>
    {notice && <p role="status" className={`admin-message${notice === "SAVED" ? "" : " error"}`}>{notice === "SAVED" ? t("Saved. The current state is shown below.", "已儲存，下方顯示目前狀態。") : t(copy[0], copy[1])}</p>}
    <div className="live-operations-grid"><aside className="admin-card"><h3>{t("Your rooms", "直播間")}</h3><div className="live-draft-list">{drafts.map(draft => <button className={detail?.draft.id === draft.id ? "selected" : ""} key={draft.id} onClick={() => void load(draft.id)} disabled={busy}><strong>{locale === "zh-Hant" ? draft.payload.titleZh || draft.payload.title : draft.payload.title}</strong><span>{draft.state === "published" ? t("Published", "已公開") : draft.state === "requested" ? t("Awaiting producer", "等待製作人") : t("Private draft", "私人草稿")} · {t("Revision", "版本")} {draft.revision}</span></button>)}</div>{!drafts.length && <p>{t("No rooms yet.", "尚無直播間。")}</p>}<div className="live-ops-actions"><button disabled={busy || page === 0} onClick={() => void list(page - 1).catch(() => setNotice("LIVE_OPERATION_FAILED"))}>{t("Previous", "上一頁")}</button><button disabled={busy || (page + 1) * 25 >= count} onClick={() => void list(page + 1).catch(() => setNotice("LIVE_OPERATION_FAILED"))}>{t("Next", "下一頁")}</button></div></aside>
      <section className="admin-card"><div className="admin-card-heading"><h3>{detail ? t("Room draft", "直播間草稿") : t("Prepare a room", "準備直播間")}</h3>{detail && <button className="text-link" disabled={busy} onClick={() => void load(detail.draft.id)}>{t("Reload saved version", "載入已儲存版本")}</button>}</div>
      <form className="admin-form" onSubmit={save}><fieldset disabled={!writable || busy} className="live-fields"><div className="field-row"><label>{t("English title", "英文名稱")}<input value={payload.title} required maxLength={180} onChange={event => change("title", event.target.value)} /></label><label>{t("Traditional Chinese title", "繁體中文名稱")}<input value={payload.titleZh} required maxLength={180} onChange={event => change("titleZh", event.target.value)} /></label></div><label>{t("Room address", "直播間網址名稱")}<input value={payload.slug} required maxLength={120} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" onChange={event => change("slug", event.target.value)} /></label>
      <div className="field-row"><label>{t("English description", "英文簡介")}<textarea value={payload.description} maxLength={5000} onChange={event => change("description", event.target.value)} /></label><label>{t("Traditional Chinese description", "繁體中文簡介")}<textarea value={payload.descriptionZh} maxLength={5000} onChange={event => change("descriptionZh", event.target.value)} /></label></div>
      <div className="field-row"><label>{t("Host identity", "主播身分")}<select required value={payload.kolId} disabled={role === "kol"} onChange={event => { change("kolId", event.target.value); change("hostName", kols.find(kol => kol.id === event.target.value)?.displayName || ""); }}><option value="">{t("Select host", "選擇主播")}</option>{activeHosts.map(kol => <option value={kol.id} key={kol.id}>{localize(kol.displayName)}</option>)}</select></label><label>{t("Host display name", "主播顯示名稱")}<input value={payload.hostName} required maxLength={120} onChange={event => change("hostName", event.target.value)} /></label></div>
      <div className="field-row"><label>{t("Platform", "平台")}<select value={payload.platform} disabled={!operator && Boolean(detail)} onChange={event => change("platform", event.target.value as LiveDraftPayload["platform"])}><option value="youtube">YouTube</option><option value="facebook">Facebook</option><option value="instagram">Instagram</option><option value="tiktok">TikTok</option><option value="external">{t("Other source", "其他來源")}</option></select></label><label>{t("Requested public state", "希望公開的狀態")}<select value={payload.status} onChange={event => change("status", event.target.value as LiveDraftPayload["status"])}><option value="scheduled">{t("Scheduled", "已排程")}</option><option value="live">{t("Live", "直播中")}</option><option value="ended">{t("Ended", "已結束")}</option></select></label></div>
      <label>{t("Official source URL", "官方來源網址")}<input type="url" required value={payload.externalUrl} disabled={!operator && Boolean(detail)} onChange={event => change("externalUrl", event.target.value)} /></label><label>{t("Video ID, if needed", "影片識別碼（如需要）")}<input value={payload.embedId || ""} disabled={!operator && Boolean(detail)} maxLength={200} onChange={event => change("embedId", event.target.value || null)} /></label>
      <div className="field-row"><label>{t("Start time (your device timezone)", "開始時間（依裝置時區）")}<input type="datetime-local" required value={dateInput(payload.startsAt)} onChange={event => { if (event.target.value) change("startsAt", new Date(event.target.value).toISOString()); }} /></label><label>{t("End time (optional)", "結束時間（可選）")}<input type="datetime-local" value={dateInput(payload.endsAt)} onChange={event => change("endsAt", event.target.value ? new Date(event.target.value).toISOString() : null)} /></label></div><label>{t("Approved poster URL (optional)", "核准封面網址（可選）")}<input type="url" value={payload.posterUrl || ""} onChange={event => change("posterUrl", event.target.value || null)} /></label>
      <fieldset className="product-picker"><legend>{t("Approved merchandise · choose up to 30", "核准商品 · 最多選擇 30 件")}</legend>{approved.map(product => <label key={product.id}><input type="checkbox" checked={payload.productIds.includes(product.id)} disabled={!payload.productIds.includes(product.id) && payload.productIds.length >= 30} onChange={event => change("productIds", event.target.checked ? [...payload.productIds, product.id] : payload.productIds.filter(id => id !== product.id))} /><span>{productTitle(product, locale, localize)}<small>{product.sku}</small></span></label>)}{!approved.length && <p>{t("Approve real merchandise in the batch workspace first.", "請先在批次工作區核准真實商品。")}</p>}</fieldset>
      {payload.productIds.length > 0 && <ol className="live-rail-order">{payload.productIds.map((id, index) => <li key={id}><span>{products.find(product => product.id === id)?.sku || t("Unavailable item", "無法提供的商品")}</span><button type="button" disabled={index === 0} onClick={() => move(id, -1)} aria-label={t("Move earlier", "向前移動")}>↑</button><button type="button" disabled={index === payload.productIds.length - 1} onClick={() => move(id, 1)} aria-label={t("Move later", "向後移動")}>↓</button></li>)}</ol>}
      <button type="submit" className="button">{t("Save private draft", "儲存私人草稿")}</button></fieldset></form>
      {detail && <><div className="live-ops-actions"><button className="button button-secondary" disabled={busy || dirty || !writable || detail.draft.state === "published"} onClick={() => void action({ action: "request", revision: detail.draft.revision })}>{t("Request publication", "申請公開")}</button>{detail.draft.published_revision && <a className="text-link" href={`/live/${detail.draft.payload.slug}`} target="_blank" rel="noopener noreferrer">{t("View room", "查看直播間")} ↗</a>}</div>
      {operator && <section className="live-source-review"><h3>{t("Verify this broadcast", "驗證本場播放來源")}</h3><p>{t("This is a producer's recorded check, not automatic platform certification. Test the source on this website before confirming it. Every saved edit requires a fresh check.", "這是製作人的檢查紀錄，不是平台自動認證。確認前請在本網站測試來源；每次儲存修改均須重新檢查。")}</p><a href={detail.draft.payload.externalUrl} target="_blank" rel="noopener noreferrer" className="text-link">{t("Open official source", "開啟官方來源")} ↗</a><label>{t("Verified viewing method", "已驗證觀看方式")}<select value={mode} onChange={event => setMode(event.target.value as typeof mode)}><option value="external_link">{t("Official source link", "官方來源連結")}</option>{["youtube", "facebook"].includes(detail.draft.payload.platform) && <option value="embedded">{t("Embedded player", "嵌入播放器")}</option>}</select></label>{mode === "embedded" && previewEmbed?.kind === "iframe" && <iframe className="live-source-preview" src={previewEmbed.src} title={t("Broadcast verification preview", "直播驗證預覽")} allow={previewEmbed.allow} allowFullScreen referrerPolicy="strict-origin-when-cross-origin" />}<label>{t("Device and result notes", "裝置及結果備註")}<input maxLength={300} value={deviceNote} onChange={event => setDeviceNote(event.target.value)} /></label><label className="live-check"><input type="checkbox" checked={rights} onChange={event => setRights(event.target.checked)} />{t("The host has authorized this source and its use here.", "主播已授權此來源及在此使用。")}</label><label className="live-check"><input type="checkbox" checked={playback} onChange={event => setPlayback(event.target.checked)} />{t("I tested the selected viewing method on the production domain.", "我已在正式網域測試所選觀看方式。")}</label><div className="live-ops-actions"><button className="button button-secondary" disabled={busy || dirty || !rights || !playback || !deviceNote.trim()} onClick={() => void action({ action: "verify", revision: detail.draft.revision, mode, deviceNote, rightsConfirmed: true, playbackConfirmed: true })}>{t("Record source check", "記錄來源檢查")}</button><button className="button" disabled={busy || dirty || !detail.sourceCheck} onClick={() => void action({ action: "publish", revision: detail.draft.revision })}>{t("Publish verified revision", "公開已驗證版本")}</button></div>{detail.sourceCheck && <small>{t("Source check recorded for this revision; publication checks freshness again.", "此版本已有來源檢查紀錄，公開時會再檢查有效期限。")}</small>}</section>}
      {writable && detail.control && <section className="live-source-review"><h3>{t("Featured now", "正在介紹")}</h3><p>{t("Pin only from the published selection. Unpublished draft changes do not affect viewers.", "只可置頂已公開精選商品；未公開草稿不會影響觀眾。")}</p><div className="live-pin-list">{detail.publishedProductIds.map(id => { const product = products.find(p => p.id === id); return <button className={detail.control?.pinned_product_id === id ? "button" : "button button-secondary"} key={id} disabled={busy || dirty} onClick={() => void action({ action: "pin", stateRevision: detail.control!.revision, productId: id })}>{product ? productTitle(product, locale, localize) : t("Selected product", "精選商品")}</button>; })}<button disabled={busy || dirty || !detail.control.pinned_product_id} onClick={() => void action({ action: "pin", stateRevision: detail.control!.revision, productId: null })}>{t("Clear pin", "取消置頂")}</button></div></section>}</>}
      </section></div>
  </div>;
}
