"use client";
import {useState} from "react";
import Link from "next/link";
import {parseProductCsv} from "@/lib/ingest/products";
import {demoKols,getDemoLiveSessions} from "@/lib/data/demo";
const sample="sku,title,price,stock_qty,currency,status\nDEMO-TEE,Sample cotton tee,58.00,12,hkd,draft\nDEMO-TEA,Sample tea gift,68.00,8,hkd,draft";
export function OperationsPreview(){
 const [csv,setCsv]=useState(sample);const [result,setResult]=useState<ReturnType<typeof parseProductCsv>|null>(null);const [fileError,setFileError]=useState("");
 const sessions=getDemoLiveSessions();
 async function loadFile(event:React.ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setResult(null);if(file.size>2*1024*1024){setFileError("Maximum 2 MB / 文件不可超过 2 MB");return;}setFileError("");setCsv(await file.text());}
 function validate(){setFileError("");const parsed=parseProductCsv(csv);if(parsed.products.length>500){setFileError("Maximum 500 rows / 最多 500 行");setResult(null);return;}setResult(parsed);}
 return <div className="shell page-space"><div className="page-intro"><span className="eyebrow">OPERATIONS SANDBOX / 运营体验</span><h1>Behind the rooms · 运营台</h1><p>Try catalog validation and explore the host-to-room workflow. This public sandbox uses fictional examples only; it cannot publish products or access orders.<br/>公开演示仅含虚构资料，可测试 CSV 校验，不写入商品，也不读取真实订单。</p><Link className="text-link" href="/admin/login">Authorized operator sign-in · 正式后台 →</Link></div>
 <div className="admin-two-column"><section className="admin-card"><span className="eyebrow">01 / VALIDATE THE CATALOG</span><h2>Batch listing · 批量上货</h2><p>Missing status becomes draft. Validation happens in this browser; no file is uploaded. 缺省状态为草稿，文件仅在浏览器内校验。</p><label className="preview-file">Choose CSV / 选择文件<input type="file" accept=".csv,text/csv" onChange={loadFile}/></label><textarea className="csv-editor" aria-label="CSV content / CSV 内容" value={csv} onChange={e=>{setCsv(e.target.value);setResult(null);}} rows={8}/><div className="hero-actions"><button className="button" onClick={validate}>Validate CSV · 校验</button><button className="button button-secondary" onClick={()=>{setCsv(sample);setResult(null);setFileError("");}}>Reset sample · 重置</button></div>{fileError&&<p role="alert" className="form-error">{fileError}</p>}{result&&<div className="preview-result" aria-live="polite">{result.issues.length?<><h3>Needs correction · 需要修正</h3><ul>{result.issues.map((i,n)=><li key={n}>Row / 行 {i.row}: {i.message}</li>)}</ul></>:<><h3>{result.products.length} valid rows · 行通过校验</h3><div className="admin-table-wrap"><table><thead><tr><th>SKU</th><th>Product</th><th>Price</th><th>Status</th></tr></thead><tbody>{result.products.map(p=><tr key={p.sku}><td>{p.sku}</td><td>{p.title}</td><td>{(p.priceAmount/100).toFixed(2)} {p.currency.toUpperCase()}</td><td>{p.status}</td></tr>)}</tbody></table></div><p>Preview complete. Nothing saved. 校验完成，未写入任何资料。</p></>}</div>}</section>
 <section className="admin-card"><span className="eyebrow">02 / MATCH HOSTS, ROOMS & PRODUCTS</span><h2>Independent rooms · 独立直播间</h2>{demoKols.map(k=><article className="host-profile" key={k.id}><span className="host-avatar">{k.displayName.slice(0,1)}</span><div><strong>{k.displayName}</strong><p>Fictional profile · 虚构资料</p>{sessions.filter(s=>s.kol?.id===k.id).map(s=><Link className="text-link" key={s.id} href={`/live/${s.slug}`}>{s.platform} · {s.products.length} products / 件商品 →</Link>)}</div></article>)}<hr/><span className="eyebrow">03 / VERIFY BEFORE SELLING</span><h2>Orders & payments · 订单与支付</h2><p>No simulated sales or revenue. Checkout stays disabled until inventory reservations, payment credentials and the full webhook lifecycle are verified. 不虚构销量；库存锁定与支付闭环验证完成前不收款。</p><Link className="text-link" href="/cart">Try the shopping bag · 体验购物袋 →</Link></section></div></div>;
}
