"use client";
import { useState } from "react";
import Link from "next/link";
import { parseProductCsv } from "@/lib/ingest/products";
import { demoKols, getDemoLiveSessions } from "@/lib/data/demo";
import { useLocale } from "@/components/i18n/locale-provider";
import { adminError, adminStatus } from "./admin-language";
export function OperationsPreview() {
  const { locale, t, localize } = useLocale();
  const sample = `sku,title,price,stock_qty,currency,status\nDEMO-TEE,${t("Sample cotton tee", "棉質上衣範例")},58.00,12,hkd,draft\nDEMO-TEA,${t("Sample tea gift", "茶禮範例")},68.00,8,hkd,draft`;
  const [csv, setCsv] = useState(sample); const [result, setResult] = useState<ReturnType<typeof parseProductCsv> | null>(null); const [fileError, setFileError] = useState("");
  const sessions = getDemoLiveSessions();
  async function loadFile(event: React.ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]; if (!file) return; setResult(null);
    if (file.size > 2 * 1024 * 1024) { setFileError("Maximum 2 MB"); return; }
    setFileError(""); try { setCsv(await file.text()); } catch { setFileError("Could not read this file."); }
  }
  function validate() { setFileError(""); const parsed = parseProductCsv(csv); if (parsed.products.length > 500) { setFileError("Maximum 500 rows"); setResult(null); return; } setResult(parsed); }
  return <div className="shell page-space"><div className="page-intro"><span className="eyebrow">{t("OPERATIONS PREVIEW", "營運預覽")}</span><h1>{t("Behind the rooms", "直播間的幕後工作")}</h1><p>{t("Try catalog validation and explore the host-to-room workflow. This public preview uses fictional examples only; it cannot publish products or access orders.", "測試商品目錄驗證，並了解主播與直播間的工作流程。公開預覽只使用虛構範例，無法發布商品或存取訂單。")}</p><Link className="text-link" href="/admin/login">{t("Operator sign-in →", "營運登入 →")}</Link></div>
    <div className="admin-two-column"><section className="admin-card"><span className="eyebrow">{t("01 / VALIDATE THE CATALOG", "01 / 驗證商品目錄")}</span><h2>{t("Batch listing", "批量上架")}</h2><p>{t("Missing status becomes draft. Validation happens in this browser; no file is uploaded.", "未填寫狀態的商品會設為草稿。驗證只在此瀏覽器進行，不會上傳檔案。")}</p><label className="preview-file">{t("Choose CSV", "選擇 CSV 檔案")}<input type="file" accept=".csv,text/csv" onChange={loadFile} /></label><textarea className="csv-editor" aria-label={t("CSV content", "CSV 內容")} value={csv} onChange={e => { setCsv(e.target.value); setResult(null); }} rows={8} /><div className="hero-actions"><button className="button" onClick={validate}>{t("Validate CSV", "驗證 CSV")}</button><button className="button button-secondary" onClick={() => { setCsv(sample); setResult(null); setFileError(""); }}>{t("Reset sample", "重設範例")}</button></div>{fileError && <p role="alert" className="form-error">{adminError(fileError, locale)}</p>}{result && <div className="preview-result" aria-live="polite">{result.issues.length ? <><h3>{t("Needs correction", "需要修正")}</h3><ul>{result.issues.map((issue, index) => <li key={index}>{t(`Row ${issue.row}`, `第 ${issue.row} 行`)}: {adminError(issue.message, locale)}</li>)}</ul></> : <><h3>{t(`${result.products.length} valid rows`, `${result.products.length} 行通過驗證`)}</h3><div className="admin-table-wrap"><table><thead><tr><th>SKU</th><th>{t("Product", "商品")}</th><th>{t("Price", "價格")}</th><th>{t("Status", "狀態")}</th></tr></thead><tbody>{result.products.map(p => <tr key={p.sku}><td>{p.sku}</td><td>{p.title}</td><td>{(p.priceAmount / 100).toFixed(2)} {p.currency.toUpperCase()}</td><td>{adminStatus(p.status, locale)}</td></tr>)}</tbody></table></div><p>{t("Validation complete. Nothing saved.", "驗證完成，未儲存任何資料。")}</p></>}</div>}</section>
      <section className="admin-card"><span className="eyebrow">{t("02 / MATCH HOSTS, ROOMS & PRODUCTS", "02 / 配對主播、直播間及商品")}</span><h2>{t("Independent rooms", "獨立直播間")}</h2>{demoKols.map(k => <article className="host-profile" key={k.id}><span className="host-avatar">{localize(k.displayName).slice(0, 1)}</span><div><strong>{localize(k.displayName)}</strong><p>{t("Fictional profile", "虛構人物資料")}</p>{sessions.filter(s => s.kol?.id === k.id).map(s => <Link className="text-link" key={s.id} href={`/live/${s.slug}`}>{adminStatus(s.platform, locale)} · {t(`${s.products.length} products`, `${s.products.length} 件商品`)} →</Link>)}</div></article>)}<hr /><span className="eyebrow">{t("03 / VERIFY BEFORE SELLING", "03 / 銷售前完成驗證")}</span><h2>{t("Orders & payments", "訂單與付款")}</h2><p>{t("No simulated sales or revenue. Checkout stays disabled until inventory reservations, payment credentials and the full webhook lifecycle are verified.", "此處不模擬銷量或營收。庫存預留、付款憑證及完整付款通知流程通過驗證前，結帳功能維持關閉。")}</p><Link className="text-link" href="/cart">{t("Try the shopping bag →", "體驗購物袋 →")}</Link></section></div></div>;
}
