"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import { useLocale } from "@/components/i18n/locale-provider";
import type { OperationalOrder } from "@/lib/orders/contracts";
export function OrderWorkspace({role}:{role:string}){
 const {t,locale}=useLocale();const[items,setItems]=useState<OperationalOrder[]>([]);const[count,setCount]=useState(0);const[page,setPage]=useState(0);const[status,setStatus]=useState("");const[search,setSearch]=useState("");const[notice,setNotice]=useState("");const[busy,setBusy]=useState(false);const sequence=useRef(0);
 const load=useCallback(async()=>{const current=++sequence.current;try{const params=new URLSearchParams({page:String(page),status,search});const response=await fetch(`/api/admin/orders?${params}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw Error();if(current===sequence.current){setItems(data.items);setCount(data.count);setNotice("");}}catch{if(current===sequence.current)setNotice("load");}},[page,status,search]);
 useEffect(()=>{const counter=sequence;const initial=setTimeout(()=>void load(),0);return()=>{clearTimeout(initial);counter.current++;};},[load]);
 const requestKeys=useRef(new Map<string,string>());
 async function act(order:OperationalOrder,action:string,data:Record<string,unknown>){setBusy(true);setNotice("");const payload={action,revision:order.revision,data};const fingerprint=JSON.stringify([order.id,payload]);const requestId=requestKeys.current.get(fingerprint)||crypto.randomUUID();requestKeys.current.set(fingerprint,requestId);try{const response=await fetch(`/api/admin/orders/${order.id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...payload,requestId})});if(!response.ok)throw Error();requestKeys.current.delete(fingerprint);await load();}catch{setNotice("operation");}finally{setBusy(false);}}
 return <section className="admin-table-card"><div className="admin-card-heading"><div><span className="eyebrow">{t("ORDER OPERATIONS","訂單作業")}</span><h2>{t("From paid to delivered","從付款到送達")}</h2></div><button className="text-link" onClick={()=>void load()} disabled={busy}>{t("Refresh","重新整理")}</button></div><p>{t("Only verified paid orders can be packed or shipped. Refund approval records a decision; it does not move money or restock products.","只有經驗證已付款的訂單才可包裝或寄出。退款核准僅記錄決定，不會轉移款項或補回庫存。")}</p><div className="admin-form-grid"><label>{t("Payment state","付款狀態")}<select value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="">{t("All available orders","所有可查看訂單")}</option>{[["pending","Pending","待付款"],["paid","Paid","已付款"],["review","Needs review","待跟進"],["cancelled","Cancelled","已取消"],["refunded","Refunded","已退款"]].map(([value,en,zh])=><option key={value} value={value}>{t(en,zh)}</option>)}</select></label><label>{t("Order ID begins with","訂單編號開頭")}<input value={search} maxLength={36} onChange={e=>{if(/^[a-fA-F0-9-]*$/.test(e.target.value)){setSearch(e.target.value);setPage(0);}}}/></label></div>{notice&&<p role="alert">{notice==="load"?t("Orders could not be loaded. Check your access and try again.","未能載入訂單，請檢查權限後再試。"):t("The update could not be confirmed. Refresh and check the current state before retrying.","未能確認更新，請重新整理並檢查最新狀態後再試。")}</p>}
 {items.map(order=><OrderCard key={`${order.id}-${order.revision}`} order={order} superAdmin={role==="super_admin"} busy={busy} onAction={(action,data)=>act(order,action,data)}/>)}{!items.length&&!notice&&<p>{t("No orders in this queue.","此佇列暫無訂單。")}</p>}<div className="batch-actions"><button disabled={!page||busy} onClick={()=>setPage(page-1)}>{t("Previous","上一頁")}</button><span>{new Intl.NumberFormat(locale==="en"?"en-HK":"zh-HK").format(count)} {t("orders","筆訂單")} · {page+1}/{Math.max(1,Math.ceil(count/25))}</span><button disabled={(page+1)*25>=count||busy} onClick={()=>setPage(page+1)}>{t("Next","下一頁")}</button></div></section>;
}
function OrderCard({order,superAdmin,busy,onAction}:{order:OperationalOrder;superAdmin:boolean;busy:boolean;onAction:(action:string,data:Record<string,unknown>)=>Promise<void>}){
 const{t,locale}=useLocale();const[carrier,setCarrier]=useState("");const[tracking,setTracking]=useState("");const[reason,setReason]=useState("");const[note,setNote]=useState("");const[userId,setUserId]=useState("");const[support,setSupport]=useState(false);const[fulfillment,setFulfillment]=useState(false);
 const statuses:Record<string,[string,string]>={pending:["Pending payment","待付款"],paid:["Paid","已付款"],failed:["Failed","付款失敗"],cancelled:["Cancelled","已取消"],refunded:["Refunded","已退款"],review:["Payment review","付款待跟進"],unfulfilled:["Not packed","未包裝"],packed:["Packed","已包裝"],shipped:["Shipped","已寄出"],delivered:["Delivered","已送達"],requested:["Requested","已申請"],approved:["Approved; execution pending","已核准，待執行"],rejected:["Rejected","已拒絕"]};const label=(value:string)=>statuses[value]?t(...statuses[value]):t("Unknown","未知");
 const refundHold=order.fulfillmentOnHold;
 return <article className="admin-order-card"><header><h3>{order.id}</h3><p>{label(order.status)} · {label(order.fulfillmentStatus)} · {new Intl.NumberFormat(locale==="en"?"en-HK":"zh-HK",{style:"currency",currency:order.currency.toUpperCase()}).format((order.totalAmount??order.subtotalAmount)/100)}</p></header>{order.customerName&&<p>{order.customerName}</p>}{order.customerEmail&&<p>{order.customerEmail}</p>}{order.shippingAddress&&<p>{Object.values(order.shippingAddress).filter(value=>typeof value==="string").join(", ")}</p>}<ul>{order.items.map((item,index)=><li key={`${item.sku}-${index}`}>{item.sku} · {item.title} × {item.quantity}</li>)}</ul>{order.trackingNumber&&<p>{order.carrier} · {order.trackingNumber}</p>}
 {refundHold&&<p role="status">{t("Fulfillment is on hold while a refund is under review or awaiting execution.","退款審閱或等待執行期間，出貨作業暫停。")}</p>}{order.canFulfill&&order.status==="paid"&&<div className="admin-form-grid">{order.fulfillmentStatus==="unfulfilled"&&<button className="button" disabled={busy||refundHold} onClick={()=>void onAction("pack",{})}>{t("Mark packed","標記已包裝")}</button>}{order.fulfillmentStatus==="packed"&&<form onSubmit={e=>{e.preventDefault();void onAction("ship",{carrier,trackingNumber:tracking});}}><label>{t("Carrier","物流商")}<input value={carrier} onChange={e=>setCarrier(e.target.value)} required maxLength={80}/></label><label>{t("Tracking number","物流編號")}<input value={tracking} onChange={e=>setTracking(e.target.value)} required maxLength={160}/></label><button className="button" disabled={busy||refundHold}>{t("Confirm shipment","確認寄出")}</button></form>}{order.fulfillmentStatus==="shipped"&&<button className="button" disabled={busy||refundHold} onClick={()=>void onAction("deliver",{})}>{t("Confirm delivery","確認送達")}</button>}</div>}
 {order.canRequestRefund&&order.status==="paid"&&!refundHold&&<details><summary>{t("Request a refund review","申請退款審閱")}</summary><form onSubmit={e=>{e.preventDefault();void onAction("request_refund",{reason});}}><label>{t("Reason","原因")}<textarea value={reason} onChange={e=>setReason(e.target.value)} required maxLength={1000}/></label><button className="button button-secondary" disabled={busy}>{t("Submit request","提交申請")}</button></form></details>}
 {order.refundRequests.map(refund=><div key={refund.id}><strong>{label(refund.status)}</strong><p>{refund.reason}</p>{refund.reviewNote&&<p>{refund.reviewNote}</p>}{superAdmin&&refund.status==="requested"&&<div><label>{t("Decision note","決定備註")}<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={1000}/></label><div className="batch-actions"><button disabled={busy||!note.trim()} onClick={()=>void onAction("review_refund",{refundId:refund.id,decision:"approved",note})}>{t("Approve request","核准申請")}</button><button disabled={busy||!note.trim()} onClick={()=>void onAction("review_refund",{refundId:refund.id,decision:"rejected",note})}>{t("Reject request","拒絕申請")}</button></div></div>}</div>)}
 {superAdmin&&<details><summary>{t("Assign order access","分派訂單權限")}</summary><form onSubmit={e=>{e.preventDefault();void onAction("assign",{userId,support,fulfillment});}}><label>{t("Team member ID","團隊成員編號")}<input value={userId} onChange={e=>setUserId(e.target.value)} required pattern="[0-9a-fA-F-]{36}"/></label><label><input type="checkbox" checked={support} onChange={e=>setSupport(e.target.checked)}/>{t("Customer support","顧客服務")}</label><label><input type="checkbox" checked={fulfillment} onChange={e=>setFulfillment(e.target.checked)}/>{t("Fulfillment","出貨作業")}</label><button disabled={busy}>{t("Save assignment","儲存分派")}</button><small>{t("Clearing both permissions removes access. Only active order operators may be assigned.","取消兩項權限即可移除存取權，僅可分派給有效的訂單作業人員。")}</small></form></details>}</article>;
}
