"use client";
import { useRef, useState } from "react";
import { useLocale } from "@/components/i18n/locale-provider";
import { STAFF_ROLES, type StaffRole } from "@/lib/staff/permissions";
import { roleLabels, staffMessage } from "@/lib/staff/messages";
export type StaffInvitation = { id: string; email: string; role: StaffRole; user_id: string | null; status: string; created_at: string };
export function StaffInvite({ hosts, invitations }: { hosts: { id: string; display_name: string }[]; invitations: StaffInvitation[] }) {
 const { locale, t } = useLocale(); const [role, setRole] = useState<StaffRole>("analyst"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const request = useRef<string | null>(null);
 async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setBusy(true); const form = new FormData(event.currentTarget); request.current ||= crypto.randomUUID(); try { const response = await fetch("/api/admin/team/invite", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ requestId: request.current, email: form.get("email"), role, kolId: role === "kol" ? form.get("kolId") : null }) }); const data = await response.json(); if (!response.ok) { setError(data.code || "INVITE_FAILED"); return; } window.location.reload(); } catch { setError("INVITE_FAILED"); } finally { setBusy(false); } }
 const status = (value: string) => value === "ready" ? t("Invited; access assigned", "已邀請並設定權限") : value === "failed" ? t("Send failed", "寄送失敗") : value === "membership_pending" ? t("Access review required", "權限待覆核") : t("Delivery not confirmed", "尚未確認寄送結果");
 return <section className="admin-card"><h2>{t("Invite a staff member", "邀請員工")}</h2><p>{t("Send an invitation to a specific email and assign its role. No access is granted until the membership transaction succeeds. Supabase email delivery must be configured.", "向指定電子郵件寄送邀請並設定角色。員工權限成功寫入後才會授予存取權。Supabase 郵件寄送功能必須已完成設定。")}</p><form className="admin-form" onSubmit={submit}><label>{t("Email", "電子郵件")}<input name="email" type="email" maxLength={254} required /></label><label>{t("Role", "角色")}<select value={role} onChange={e => setRole(e.target.value as StaffRole)}>{STAFF_ROLES.map(value => <option key={value} value={value}>{roleLabels[value][locale === "en" ? 0 : 1]}</option>)}</select></label>{role === "kol" && <label>{t("Host profile", "主播檔案")}<select name="kolId" required><option value="">{t("Select host", "選擇主播")}</option>{hosts.map(host => <option key={host.id} value={host.id}>{host.display_name}</option>)}</select></label>}<button className="button" disabled={busy}>{t("Send staff invitation", "寄送員工邀請")}</button>{error && <p role="alert">{staffMessage(error, locale)}</p>}</form>{invitations.length > 0 && <><h3>{t("Recent invitations", "最近邀請")}</h3><div className="admin-table-wrap"><table><thead><tr><th>{t("Email", "電子郵件")}</th><th>{t("Role", "角色")}</th><th>{t("Status", "狀態")}</th><th>{t("Account ID", "帳戶識別碼")}</th></tr></thead><tbody>{invitations.map(invite => <tr key={invite.id}><td>{invite.email}</td><td>{roleLabels[invite.role][locale === "en" ? 0 : 1]}</td><td>{status(invite.status)}</td><td><code>{invite.user_id || "—"}</code></td></tr>)}</tbody></table></div></>}</section>;
}
