"use client";
import { useState } from "react";
import { useLocale } from "@/components/i18n/locale-provider";
import { staffMessage } from "@/lib/staff/messages";
export function StaffMfa() {
 const { locale, t } = useLocale(); const [factor, setFactor] = useState(""); const [qr, setQr] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
 async function send(body: unknown) { setError(""); setBusy(true); try { const r = await fetch("/api/admin/mfa", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await r.json(); if (!r.ok) { setError(data.code || "STAFF_OPERATION_FAILED"); return; } if (data.redirect) { window.location.assign(data.redirect); return; } setFactor(data.factorId); setQr(typeof data.qrCode === "string" ? data.qrCode : ""); } catch { setError("STAFF_OPERATION_FAILED"); } finally { setBusy(false); } }
 return <section className="admin-login-card"><span className="eyebrow">{t("ACCOUNT SECURITY", "帳戶安全")}</span><h1>{t("Verify your authenticator", "驗證你的驗證器")}</h1><p>{t("Use a time-based authenticator app. If this is your first sign-in, scan the setup code privately, then enter its six-digit code.", "請使用動態驗證器應用程式。首次登入時，請私下掃描設定碼，再輸入六位數驗證碼。")}</p>{!factor ? <button className="button" disabled={busy} onClick={() => send({ action: "setup" })}>{t("Continue setup or verification", "繼續設定或驗證")}</button> : <form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void send({ action: "verify", factorId: factor, code: form.get("code") }); }}>{qr && <img style={{ width: 220, maxWidth: "100%" }} src={qr.startsWith("data:image/svg+xml") ? qr : `data:image/svg+xml;charset=utf-8,${encodeURIComponent(qr)}`} alt={t("Private authenticator setup QR code", "私密驗證器設定二維碼")} />}<label>{t("Six-digit code", "六位數驗證碼")}<input name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required /></label><button className="button" disabled={busy}>{t("Verify and sign in", "驗證並登入")}</button></form>}{error && <p role="alert" className="form-error">{staffMessage(error, locale)}</p>}<p><a href="/admin/login">{t("Return to sign-in", "返回登入")}</a></p></section>;
}
