"use client";
import { useState } from "react";
import { useLocale } from "@/components/i18n/locale-provider";
import { STAFF_ROLES, type StaffRole } from "@/lib/staff/permissions";
import { roleLabels, staffMessage } from "@/lib/staff/messages";
export type TeamMember = { user_id: string; role: StaffRole; active: boolean; kol_id: string | null; updated_at: string };
export function StaffTeam({ members, hosts, currentId }: { members: TeamMember[]; hosts: { id: string; display_name: string }[]; currentId: string }) {
 const { locale, t } = useLocale(); const [role, setRole] = useState<StaffRole>("analyst"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
 async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const f = new FormData(event.currentTarget); try { const r = await fetch("/api/admin/team", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId: f.get("userId"), role, active: f.get("active") === "on", kolId: role === "kol" ? f.get("kolId") : null }) }); const result = await r.json(); if (!r.ok) { setError(result.code || "STAFF_OPERATION_FAILED"); return; } window.location.reload(); } catch { setError("STAFF_OPERATION_FAILED"); } finally { setBusy(false); } }
 return <div className="admin-two-column"><section className="admin-card"><h2>{t("Assign staff access", "設定員工權限")}</h2><p>{t("Assign an existing named account. This form does not create accounts or send invitations. Your own access must be changed by another super administrator.", "為現有具名帳戶設定權限。此表格不會建立帳戶或寄送邀請。你自己的權限必須由另一位超級管理員修改。")}</p><form className="admin-form" onSubmit={submit}><label>{t("Account user ID", "帳戶使用者識別碼")}<input name="userId" required pattern="[0-9a-fA-F-]{36}" maxLength={36} /></label><label>{t("Role", "角色")}<select value={role} onChange={e => setRole(e.target.value as StaffRole)}>{STAFF_ROLES.map(value => <option key={value} value={value}>{roleLabels[value][locale === "en" ? 0 : 1]}</option>)}</select></label>{role === "kol" && <label>{t("Assigned host profile", "所屬主播檔案")}<select name="kolId" required><option value="">{t("Select host", "選擇主播")}</option>{hosts.map(host => <option key={host.id} value={host.id}>{host.display_name}</option>)}</select></label>}<label><input type="checkbox" name="active" defaultChecked /> {t("Active membership", "啟用權限")}</label><button className="button" disabled={busy}>{t("Save membership", "儲存權限")}</button>{error && <p className="form-error" role="alert">{staffMessage(error, locale)}</p>}</form></section><section className="admin-card"><h2>{t("Current team", "現有團隊")}</h2><div className="admin-table-wrap"><table><thead><tr><th>{t("Account", "帳戶")}</th><th>{t("Role", "角色")}</th><th>{t("Status", "狀態")}</th></tr></thead><tbody>{members.map(member => <tr key={member.user_id}><td><code>{member.user_id}</code>{member.user_id === currentId && <small>{t("Your account", "你的帳戶")}</small>}{member.kol_id && <small>{hosts.find(host => host.id === member.kol_id)?.display_name || member.kol_id}</small>}</td><td>{roleLabels[member.role][locale === "en" ? 0 : 1]}</td><td>{member.active ? t("Active", "啟用") : t("Revoked", "已撤銷")}</td></tr>)}</tbody></table></div><p>{t("The latest 100 memberships are shown. Role and access changes are audited and take effect on the next request.", "顯示最近 100 筆員工權限。角色及權限變更會留下紀錄，並於下一次請求生效。")}</p></section></div>;
}
