"use client";
import Link from "next/link";
import { CartCount } from "@/components/cart/cart-count";
import { BrandMark } from "@/components/site/brand-mark";
import { getStoreProfile, supplierCollectionEnabled, holidayCollectionsEnabled } from "@/lib/store-profile";
import { LOCALE_NAMES, type Locale } from "@/lib/i18n";
import {useLocale} from "@/components/i18n/locale-provider";
export function SiteHeader(){
 const {locale,t,setLocale}=useLocale(); const profile=getStoreProfile();
 return <header className="site-header"><div className="shell header-inner"><BrandMark/><form className="header-search" action="/shop" role="search"><input name="q" aria-label={t("Search products","搜尋商品")} placeholder={t("Search products","搜尋商品")}/><button type="submit" aria-label={t("Search","搜尋")}><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg></button></form><div className="header-tools"><label className="language-picker"><span aria-hidden="true">🌐</span><select className="language-switch" aria-label={t("Language", "語言")} value={locale} onChange={event=>setLocale(event.target.value as Locale)}>{profile.locales.supported.map(language=><option key={language} value={language} lang={language}>{LOCALE_NAMES[language]}</option>)}</select></label><Link className="cart-link" href="/cart" aria-label={t("Shopping bag","購物袋")}><svg width="21" height="23" viewBox="0 0 24 26" fill="none" stroke="currentColor" strokeWidth="1.4" aria-hidden="true"><path d="M4 8h16l1 16H3L4 8Z"/><path d="M8 9V6a4 4 0 0 1 8 0v3"/></svg><CartCount/></Link></div></div><nav className="shell category-nav" aria-label={t("Main navigation","主要導覽")}><Link href="/shop">{t("All products","全部商品")}</Link>{supplierCollectionEnabled()&&<Link href="/shop?collection=supplier-demo">{t("New discoveries","新選好物","新しい出会い")}</Link>}<Link href="/shop?category=Apparel">{t("Clothing","服飾")}</Link><Link href="/shop?category=Lifestyle">{t("Everyday living","日常生活")}</Link><Link href="/shop?category=Travel">{t("Travel","旅行用品")}</Link><Link href="/shop?category=Gifts">{t("Gifts","心意禮品")}</Link>{holidayCollectionsEnabled()&&<Link className="nav-holiday-link" href="/collections">{t("Holiday edit","節日選物")}</Link>}<Link className="nav-room-link" href="/watch">{t("Watch & shop","觀看與選購")} <span aria-hidden="true">↗</span></Link></nav></header>;
}
