import Link from "next/link";
import {LiveBadge} from "@/components/live/live-badge";
import {ProductCard} from "@/components/product/product-card";
import {getLiveSessions,getProducts} from "@/lib/data/store";
import {productsForHoliday} from "@/lib/data/holiday-collections";
import {getLocale} from "@/lib/locale-server";
export const dynamic="force-dynamic";
export default async function HomePage(){
 const [{t,localize},products,sessions]=await Promise.all([getLocale(),getProducts(),getLiveSessions()]);
 const homeSelection = [...productsForHoliday(products, "mid-autumn").slice(0,4), ...products.slice(0,4)];
 const categories=[{name:t("Clothing","服飾"),value:"Apparel",image:"/editorial/tee.jpg"},{name:t("Everyday living","日常生活"),value:"Lifestyle",image:"/editorial/fan.jpg"},{name:t("Travel","旅行用品"),value:"Travel",image:"/editorial/bag.jpg"},{name:t("Gifts","心意禮品"),value:"Gifts",image:"/editorial/tea.jpg"}];
 return <><section className="shell editorial-hero holiday-home-hero"><div className="editorial-visual"><img src="/editorial/holiday/lotus-mooncake-box.jpg" alt={t("Lotus mooncake gift box for a moonlit reunion","月下團圓的蓮蓉月餅禮盒")}/></div><div className="editorial-copy"><span className="eyebrow">{t("MID-AUTUMN · 25 SEPTEMBER 2026","中秋 · 2026 年 9 月 25 日")}</span><h1>{t("A little sweetness.\nA little togetherness.","一點甜，\n一份團圓。")}</h1><p>{t("Mooncakes to share, tea to pour and little rituals for an evening beneath the same moon.","分享月餅、斟一杯茶，在同一輪月光下，留一晚給彼此。")}</p><Link className="button" href="/shop?collection=mid-autumn">{t("Explore moonlit reunion","探索月下團圓")} <span aria-hidden="true">→</span></Link><Link className="editorial-note text-link" href="/collections">{t("Discover the year’s holiday collections","探索一整年的節日選物")} →</Link></div></section><section className="shell category-tiles" aria-label={t("Shop by category","按分類選購")}>{categories.map(c=><Link href={`/shop?category=${c.value}`} key={c.value}><img src={c.image} alt=""/><span>{c.name}</span><span aria-hidden="true">↗</span></Link>)}</section><section className="section shell"><div className="section-heading"><div><span className="eyebrow">{t("SEASONAL & EVERYDAY","節日與日常")}</span><h2>{t("Good things, shared","好物一起分享")}</h2></div><Link className="text-link" href="/shop">{t("View all products","查看全部商品")} →</Link></div><div className="product-grid">{homeSelection.map(p=><ProductCard key={p.id} product={p}/>)}</div></section><section className="rooms-section"><div className="shell section"><div className="section-heading"><div><span className="eyebrow">{t("MEET THE SELECTION","一起探索")}</span><h2>{t("A room for your interests","找到喜歡的直播間")}</h2><p className="section-description">{t("Independent selections. One shopping bag, wherever you wander.","每個直播間各有精選，購物袋隨你自由探索。")}</p></div><Link className="text-link" href="/live">{t("Explore rooms","探索直播間")} →</Link></div><div className="home-rooms">{sessions.slice(0,3).map((s,i)=><Link href={`/live/${s.slug}`} key={s.id}><div className={`room-art room-art-${i}`}><span aria-hidden="true">{String(i+1).padStart(2,"0")}</span><img src={categories[i]?.image} alt=""/><LiveBadge status={s.status}/></div><h3>{localize(s.title)}</h3><p>{localize(s.hostName)}</p><span className="text-link">{t("Enter room","進入直播間")} →</span></Link>)}</div></div></section></>;
}
