import { PGlite } from '@electric-sql/pglite';
import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const db=new PGlite();let passed=0;
const q=(sql,args=[])=>db.query(sql,args),one=async(sql,args=[])=>(await q(sql,args)).rows[0];
const check=(name,ok)=>{assert.ok(ok,name);console.log(`PASS ${++passed}: ${name}`);};
const fails=async(fn,code)=>{try{await fn();return false;}catch(error){return String(error).includes(code);}};
await db.exec('create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,is_anonymous boolean default false);create table auth.sessions(id uuid primary key,user_id uuid,not_after timestamptz);create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);');
for(const file of readdirSync(path.join(root,'supabase/migrations')).filter(f=>f.endsWith('.sql')).sort())await db.exec(readFileSync(path.join(root,'supabase/migrations',file),'utf8'));
const actor=randomUUID();await q('insert into auth.users(id) values($1)',[actor]);await q("insert into staff_members(user_id,role) values($1,'super_admin')",[actor]);
const style=JSON.parse(readFileSync(path.join(root,'style/muji/tokens.json'),'utf8'));
const data={sku:'DEMO-CHECK',title:'Workflow check',description:'Display-only test item.',titleZh:'流程測試',descriptionZh:'僅供展示的測試商品。',category:'Lifestyle',priceAmount:100,currency:'hkd',stockQty:20};
const hash='b'.repeat(64),state=id=>one('select * from media_batch_items where id=$1',[id]);
async function create(product){const {id}=await one('select batch_create($1,$2,$3,$4::jsonb,$5::jsonb,$6) id',[actor,'Demo check','muji',JSON.stringify(style),JSON.stringify([{filename:'tea.jpg',mime:'image/jpeg',byte_size:120,product_data:product}]),randomUUID()]);return one('select * from media_batch_items where batch_id=$1',[id]);}
async function process(item){await q('select batch_finalize($1,$2,1)',[actor,item.id]);const claim=await one('select * from batch_claim(1)');const output=`${item.batch_id}/${item.id}/r1-${hash}.webp`;await q('select batch_reserve_object($1,1,$2,$3,$4,100,$5)',[item.id,claim.lease_token,'batch-processed',output,hash]);await q("select batch_processed($1,1,$2,repeat('a',64),$3,$4,repeat('c',64),'sharp-0.35.4/v1')",[item.id,claim.lease_token,hash,output]);}
const approve=(id,revision)=>q("select batch_review($1,$2,$3,'approve','')",[actor,id,revision]);
async function publish(item){const claim=await one('select * from batch_claim(1)');assert.equal(claim.id,item.id);const output=`batch/${item.id}/r${item.revision}-${hash}.webp`;await q('select batch_reserve_object($1,$2,$3,$4,$5,100,$6)',[item.id,item.revision,claim.lease_token,'product-images',output,hash]);const args=[item.id,item.revision,claim.lease_token,`https://example.supabase.co/storage/v1/object/public/product-images/${output}`,output,hash];await q('select batch_publish($1,$2,$3,$4,$5,$6)',args);await q('select batch_publish($1,$2,$3,$4,$5,$6)',args);return one('select * from products where id=$1',[item.id]);}
for(const value of ['true','false',null,1]){check(`non-boolean demo flag ${JSON.stringify(value)} rejected at intake`,await fails(()=>create({...data,isDemo:value}),'INVALID_DRAFT'));const valid=await one('select batch_valid_product($1::jsonb) ok',[JSON.stringify({...data,isDemo:value})]);check('approval validator also rejects invalid flag',valid.ok===false);}
let demo=await create({...data,isDemo:true});check('demo intake persists explicit true',demo.product_data.isDemo===true);await process(demo);await approve(demo.id,1);demo=await state(demo.id);check('demo approval binds exact revision',demo.approved_revision===1&&demo.product_data.isDemo===true);
const product=await publish(demo);check('approved demo remains demo after idempotent publication',product.is_demo===true&&product.stock_qty===20);
await q('select checkout_admission_policy_set($1,true,5,2,100)',[actor]);check('demo cannot reserve stock even with an enabled checkout policy and positive stock',await fails(()=>q('select reserve_checkout($1,$2,$3::jsonb,$4::jsonb,$5)',[randomUUID(),'f'.repeat(64),JSON.stringify([{product_id:demo.id,quantity:1}]),'{}','a'.repeat(64)]),'PRODUCT_UNAVAILABLE'));
check('blocked demo creates no order or reservation',(await one('select count(*)::int n from orders')).n===0&&(await one('select count(*)::int n from inventory_reservations')).n===0);
check('publication audit records approved demo flag',(await one("select detail from media_batch_audit where item_id=$1 and action='published'",[demo.id])).detail.is_demo===true);
for(const flag of [undefined,false]){const item=await create({...data,sku:flag===undefined?'LEGACY-REAL':'EXPLICIT-REAL',...(flag===undefined?{}:{isDemo:flag})});await process(item);await approve(item.id,1);check(`${flag===undefined?'missing':'false'} flag retains real-merchandise behavior`,(await publish(await state(item.id))).is_demo===false);}
let edited=await create({...data,sku:'REVISED-DEMO',isDemo:true});await process(edited);await approve(edited.id,1);await q('select batch_edit($1,$2,1,$3::jsonb)',[actor,edited.id,JSON.stringify({...edited.product_data,isDemo:false})]);edited=await state(edited.id);check('changing demo to real clears approval and increments revision',edited.revision===2&&edited.status==='review'&&edited.approved_by===null&&edited.approved_revision===null);
check('old revision cannot approve changed demo status',await fails(()=>approve(edited.id,1),'STALE_OR_INVALID_STATE'));check('stale publication cannot create a real item after the flag changes',await fails(()=>q('select batch_publish($1,1,$2,$3,$4,$5)',[edited.id,randomUUID(),'https://example.supabase.co/storage/v1/object/public/product-images/stale','stale',hash]),'STALE_LEASE')&&(await one('select count(*)::int n from products where id=$1',[edited.id])).n===0);check('changed status cannot be claimed before fresh approval',(await q('select * from batch_claim(1)')).rows.length===0);
check('invalid demo edit rejected without revision change',await fails(()=>q('select batch_edit($1,$2,2,$3::jsonb)',[actor,edited.id,JSON.stringify({...edited.product_data,isDemo:'false'})]),'INVALID_DRAFT')&&(await state(edited.id)).revision===2);
await approve(edited.id,2);await q('select batch_edit($1,$2,2,$3::jsonb)',[actor,edited.id,JSON.stringify({...edited.product_data,isDemo:true})]);edited=await state(edited.id);check('changing real back to demo also invalidates approval',edited.revision===3&&edited.approved_by===null);await approve(edited.id,3);check('fresh approval publishes the revised demo flag',(await publish(await state(edited.id))).is_demo===true);
for(const role of ['anon','authenticated']){await db.exec(`set role ${role}`);check(`${role} cannot publish or inspect flag validators`,await fails(()=>q('select batch_valid_draft($1::jsonb)',[JSON.stringify(data)]),'permission denied')&&await fails(()=>q('select batch_publish($1,1,$2,$3,$4,$5)',[demo.id,randomUUID(),'https://example.test','ignored',hash]),'permission denied'));await db.exec('reset role');}
console.log(JSON.stringify({passed,engine:'PGlite',managedDatabaseTouched:false}));await db.close();
