import Link from "next/link";
import {collectionForProduct,productsForHoliday} from "@/lib/data/holiday-collections";
import type {Metadata} from "next";
import {notFound} from "next/navigation";
import {AddToCartButton} from "@/components/cart/add-to-cart-button";
import {ProductCard} from "@/components/product/product-card";
import {getProductBySlug,getProducts,getLiveSessions} from "@/lib/data/store";
import {formatMoney} from "@/lib/format";
import {productImage} from "@/lib/product-image";
import {getLocale} from "@/lib/locale-server";
export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {t,localize}=await getLocale();const p=await getProductBySlug((await params).slug);return p?{title:localize(p.title),description:localize(p.description)}:{title:t("Product not found","商品不存在")};}
export default async function ProductPage({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{room?:string}>}){const {t,localize,locale}=await getLocale();const product=await getProductBySlug((await params).slug);if(!product)notFound();const roomId=(await searchParams).room;const room=roomId?(await getLiveSessions()).find(s=>s.id===roomId&&s.kol?.status==="active"&&s.products.some(p=>p.id===product.id)):undefined;const source=room?.kol?{liveSessionId:room.id,kolId:room.kol.id}:undefined;const collection=collectionForProduct(product.slug);const products=await getProducts();const related=(collection?productsForHoliday(products,collection.id):products.filter(p=>p.category===product.category)).filter(p=>p.id!==product.id).slice(0,4);
return <div className="shell page-space">{collection&&<Link className="text-link holiday-product-back" href={`/shop?collection=${collection.id}`}>← {collection.title[locale==="en"?0:1]}</Link>}<div className="product-detail"><div className="product-detail-image"><img src={productImage(product)} alt={localize(product.title)}/>{product.featured&&<span className="corner-label">{t("Selected","精選")}</span>}</div><div className="product-detail-copy"><span className="eyebrow">{localize(product.category)} · {product.sku}</span><h1>{localize(product.title)}</h1><p className="product-price">{formatMoney(product.priceAmount,product.currency)}</p><p className="product-description">{localize(product.description)}</p><div className="stock-line">{product.isDemo?t("Sample product. Not available to order.","演示商品，暫不接受訂購。"):product.stockQty>0?t(`${product.stockQty} in stock`,`${product.stockQty} 件現貨`):t("Sold out","已售罄")}</div>{room&&<p className="attribution">{t("From:","來源：")} {localize(room.hostName)}</p>}<AddToCartButton source={source} productId={product.id} disabled={product.stockQty<1}/><div className="product-promises"><div><b>01</b><span><strong>{t("Discover the details","探索商品細節")}</strong><small>{t("Get a closer look in a host’s room.","跟隨主播，仔細了解每件好物。")}</small></span></div><div><b>02</b><span><strong>{t("Keep your selection","保存心儀好物")}</strong><small>{t("Your bag stays with you as you explore.","切換直播間，購物袋隨你同行。")}</small></span></div><div><b>03</b><span><strong>{t("Preview only","僅供預覽")}</strong><small>{t("Orders and payments are not open yet.","暫未開放訂單與付款。")}</small></span></div></div></div></div>{related.length>0&&<section className="section"><div className="section-heading"><h2>{t("You may also like","你可能也喜歡")}</h2></div><div className="product-grid">{related.map(p=><ProductCard key={p.id} product={p}/>)}</div></section>}</div>;}
